### ISSUE TITLE
Section 11. 연습 프로젝트: 음식 주문앱

### ISSUE THREAD

**Issue by gdtknight** [gdtknight/udemy-react-practice#7]
<h2>Project Configuration</h2>

- [x] Project directory Structure

<h2>Add Component</h2>

 - [x] #9
 - [x] #10
 - [x] #11

<h2>Add Functionalities</h2>

 - [x] Apply Context to Cart -> #10 
 - [x] Apply Reducer to Cart -> #10 
 - [x] Apply Refs & Forward Refs to Cart -> #10 
 - [x] Apply useEffect -> #10
